# Note, this file is *NOT* reloaded by 'bundle exec jekyll serve'.
# If you change this file, restart the server.

# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Danny's Blog
email: dannysepler@gmail.com
description: Mainly code. Also sometimes not code.

# Keep "baseurl" commented, leaving just the / adds
# a double slash for some reason
# baseurl: / # the subpath of your site, e.g. /blog
url: https://blog.dannysepler.com

# Keep the title simple. https://jekyllrb.com/docs/permalinks/
permalink: /:title

github_username: dannysepler
enforce_ssl: blog.dannysepler.com
google_analytics: UA-127553091-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
